@startuml
title Component Diagram

component "PresentationLayer" as PL {
    component "WebApp" as WA
    component "DesktopApp" as DA
}

component "BusinessLayer" as BL {
    component "Správa uživatelů" as UM
    component "Správa událostí" as EM
    component "Správa týmů" as TM
}

component "DatabaseLayer" as DL {
    together {
        component "TeamGateway" as TG
        component "TeamToPlayerGateway" as TTPG
        component "UserGateway" as UG
        database MSSQL as DB
    }
    
    together {
    component "EventGateway" as EG
        folder data {
            file DB.json as JSONDB
        }
    }
}

' Presentation to BusinessLayer
DA -(0- UM
DA -(0- EM
DA -(0- TM

WA -(0- EM

' BusinessLayer to DatabaseLayer

TM -(0- TG
TM -(0- TTPG

UM -(0- UG

EM -(0- EG

' DatabaseLayer
EG -(0- JSONDB

TG -(0- DB
TTPG -(0- DB
UG -(0- DB

@enduml