@startuml
title Deployment diagram

node "Lokální PC" <<device>> as PC {
    node ".NET core 3.1" <<.NET>> as DN

    node "Microsoft SQL Server 2017" <<Database SErver>> {
        database "Database" as DB
    }

    folder "data/" {
        file "DB.json" as JSONDB
    }

    folder "SQL/" {
        file "create.sql" as CRSQL
    }

    artifact "WebApp" as WA
    artifact "DesktopApp" as DA
    artifact "BusinessLayer" as BL
    artifact "DatabaseLayer" as DBS

    WA --> DN : <<deploy>>
    DA --> DN : <<deploy>>
    BL --> DN : <<deploy>>
    DBS --> DN : <<deploy>>

    CRSQL --> DB : <<deploy>>
}
@enduml